version: '3'

services:
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_DATABASE_URL}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_SECRET}
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key": "${HASURA_JWT_SECRET}", "audience": "hasura", "issuer": "covid"}'
      HASURA_GRAPHQL_ENABLE_CONSOLE: ${HASURA_ENABLE_CONSOLE}
      HASURA_GRAPHQL_DEV_MODE: ${HASURA_DEV_MODE}
      HASURA_GRAPHQL_PG_CONNECTIONS: '40'
      HASURA_GRAPHQL_ENABLE_TELEMETRY: 'false'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: 'public'
    command:
    - graphql-engine
    - serve

  hasura-extensions:
    image: xgis/covid-hasura-extensions
    restart: always
    environment:
      COVID_DB_HOST: ${COVID_DB_HOST}
      COVID_DB_NAME: ${COVID_DB_NAME}
      COVID_DB_USER: ${COVID_DB_USER}
      COVID_DB_PASS: ${COVID_DB_PASS}
      MEDIASTACK_API_KEY: ${MEDIASTACK_API_KEY}

  web:
    image: xgis/covid-web
    restart: always
